plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-ccs-computing.github.io
baseurl: "/S21-20B"

course: "CMPTGCS 20B"
qtr: "S21"
instructor: "Richert Wang"
quarter: "Spring 2021"
piazza_url: 
gauchospace_course_page:
gradescope_class_url:

github_url: https://github.com/ucsb-ccs-computing/S21-20B

start_week: 1
start_date: 2021-03-28 00:00:00.00-7:00
num_weeks: 10
extra_exam_week: true

cal_dates: >                                                                    
  [                                                                            
    {"label":"S21 1st day of instruction", "date":"2021-03-29" },
    {"label":"Memorial Day", "date":"2021-05-31" },
    {"label":"S21 instruction ends", "date":"2021-06-04" },                    
    {"label":"S21 finals start", "date":"2021-06-07" },                        
    {"label":"S21 finals end", "date":"2021-06-11" },                          
    {"label":"S21 qtr ends", "date":"2021-06-11" }                              
  ]

kramdown:
   parse_block_html: true
   default_lang: cpp

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  info:
    output: true
    permalink: /info/:path/
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
